### ISSUE TITLE
Implement project multi target support

### ISSUE THREAD

**Issue by jamesmcroft** [MADE-Apps/MADE-App-Components#24]
I was recently listening to the Merge Conflict podcast and came across multi-targeting support and the enhancements that have been made for building and packaging these projects. 

It feels like this would be a great idea to start moving towards before the components library starts getting too big and the initial release.

**Comment by tom-made** [comment]
Heard about this too and if you're keen to take a look at it, happy for you to go ahead @jamesmcroft

**Comment by jamesmcroft** [comment]
I believe where I've got to with this so far is probably a great starting point. After actually going through this process, I've discovered that this is quite difficult right now. This is in particular with our projects which split across all platforms which have very platform specific UI such as UWP XAML files and iOS XIB files. 

For this reason, I haven't ported the UI.Controls and UI.Controls.HeaderedTextBlock projects. This might be a good discussion point.

**Comment by tom-made** [comment]
We will need to work out what the issue is that's blocking the other projects from moving across. 

Looking at the others though, it appears to work/look great so far.

I think we possibly need to have a discussion around the naming of components and how we may want to support cross platform going forwards
